#pragma once
#include <iostream>
#include <string>
#include <vector>
#include <map>
#include <assert.h>
#include <list>
#include <sstream>
#include <functional>
using namespace std;
#include "commontools.h"
#include "Singleton.h"
#include "UIEvent.h"
#include "ControllerType.h"
#include "UIViewControllerDelegate.h"
#include "UIDefine.h"
#include "Macros.h"
#include "Language.h"
#include "Resource.h"
#include "GameConfig.h"
